environment_yml = """
name: ceramic_armor_ml
channels:

conda-forge
defaults
dependencies:
python=3.10
pip
pip:

mp-api==0.41.2
pymatgen==2024.2.8
matminer==0.9.0
pandas==2.0.3
numpy==1.24.3
scikit-learn==1.3.0
xgboost==1.7.6
lightgbm==4.0.0
catboost==1.2
tensorflow==2.13.0
torch
optuna==3.3.0
hyperopt==0.2.7
matplotlib==3.7.2
seaborn==0.12.2
plotly==5.15.0
streamlit==1.25.0
fastapi==0.101.1
uvicorn==0.23.2
shap==0.42.1
joblib==1.3.1
tqdm==4.65.0
pytest==7.4.0
"""